### ISSUE TITLE
CausalTestOutcome static methods?

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#55]
Current code and that of the examples:
```
causal_test_case = CausalTestCase(control_input_configuration={waypoint_start_dist_from_effector: 0.5},
                                  expected_causal_effect=NoEffect,
                                  outcome_variables={collisions},
                                  intervention=Intervention((waypoint_start_dist_from_effector,), (2 * 0.5,), ), )
```
This does not work with the code below as `NoEffect` is not instanced:
```
test_passes = causal_test_case.expected_causal_effect.apply(causal_test_result)

TypeError: apply() missing 1 required positional argument: 'res'
```

This fix works but feels rather redundant and is not in line with the covasim example present:
```
causal_test_case = CausalTestCase(control_input_configuration={waypoint_start_dist_from_effector: 0.5},
                                  expected_causal_effect=NoEffect(),
                                  outcome_variables={collisions},
                                  intervention=Intervention((waypoint_start_dist_from_effector,), (2 * 0.5,), ), )
```

Is it worth making the `apply` method of each CausalTestOutcome static to keep in line with current examples? Or should current examples be updated?

**Comment by jmafoster1** [comment]
I had to read this a couple of times to get what you meant there. I agree that this is one of the many slightly clunky things about the framework. Python's a bit weird with static methods. It did occur to me that it might even be worth making causal test results a method rather than a class since you shouldn't really be doing stuff with them programatically. Possibly worth having a discussion with @cwild-UoS and @bobturneruk  about this to see if they have any suggestions for best practice here.
