### ISSUE TITLE
CausalTestEngine dependent on test case

### ISSUE THREAD

**Issue by rsomers1998** [CITCOM-project/CausalTestingFramework#71]
`CausalTestEngine` is currently dependent on a `CausalTestCase` as part of its constructor. This makes executing multiple tests against the same dataset a little clunky as a new `CausalTestEngine` has to be instanced for each test case. Could we instead make the `CausalTestEngine` dependent only on the data and specification and pass in the test case as part of the `execute_test` method?

Current:
```
causal_test_engine = CausalTestEngine(causal_test_case, causal_specification, data_collector)
causal_test_result = causal_test_engine.execute_test(linear_regression_estimator, 'ate')

causal_test_engine = CausalTestEngine(causal_test_case_2, causal_specification, data_collector)
causal_test_result_2 = causal_test_engine.execute_test(linear_regression_estimator, 'ate')
```

Proposed:
```
causal_test_engine = CausalTestEngine(causal_specification, data_collector)
causal_test_result = causal_test_engine.execute_test(causal_test_case, linear_regression_estimator, 'ate')
causal_test_result_2 = causal_test_engine.execute_test(causal_test_case_2, linear_regression_estimator, 'ate')
```

**Comment by AndrewC19** [comment]
Good point. I completely agree that this needs to change.

On a first glance, it makes sense to add a `causal_test_case: CausalTestCase` argument to `execute_test` instead of as part of the `CausalTestCase` constructor. 

There is one problem though. Currently, the causal test engine handles the identification procedure for a given test case (i.e. given a treatment, T, and an outcome, Y, what variables do I need to adjust for to isolate the causal effect of T on Y?) and this needs access to the treatment and control (currently via `causal_test_case`). So we will need to move the identification procedure (currently handled by `load_data` -- this should also be renamed to `identification`).

Before we commit to a design decision though, I think we should consider the use-cases that involve running multiple causal test cases on the same dataset. I can think of the following scenarios:

1) The causal test cases all focus on the same cause-effect relationship. In this case, identification needs to be performed once and then we should allow multiple "versions" of the same causal test to be ran (i.e. the same treatment and outcome, but with different control and treatment values).

2) The causal test cases focus on different cause-effect relationships. In this case, identification needs to be performed for each unique cause-effect relationship.

If we want a single instance of the `CausalTestEngine` to handle both cases, we will need a way to group tests together that focus on the same cause-effect relationship. That way, we can perform identification once for all tests concerning the same cause-effect relationship before moving onto the next set of tests. Perhaps something like a `CausalTestSuite`?
